default_install_hook_types:
  - pre-commit

default_stages:
  - pre-commit

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # endings
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix, lf]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext, md]

        # files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: fix-byte-order-marker

        # git
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: no-commit-to-branch
      - id: forbid-new-submodules

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.12
    hooks:
      - id: actionlint

ci:
  autoupdate_commit_msg: "ci: pre-commit autoupdate"
